### PR TITLE
feat: add stay alive remix for japanology ii

### PR DESCRIPTION
**Pull request by eye-wave**
i hope this is what you meant by PR it into official.json

### CODE REVIEW

**Comment by FlafyDev** [comment]
Thanks! got some questions

Why add 4 NONGs that lead to different youtube videos of seemingly the same song? Why not one?

Also it seems this song is also used in another popular level "Fallen Empress". The mod will prompt to change the default song there too.. I could add a field in the json to only show the NONG by level id, but jukebox will still change the song for all levels that use it. Not sure what to do about that

**Comment by eye-wave** [comment]
i based my commit based on how your official indexes looked like, so i kinda had to guess how its done.

about the "song collision", there is literally a yasobi song swapped for a bossfight song in a easy demon "adust" in the death gauntlet

**Comment by eye-wave** [comment]
potential fix for this would be to just allow reverting to original song.

**Comment by FlafyDev** [comment]
Your json is fine, it's just that you added the same song(same song, different yt url) 4 different  times. I suggest just delete 3 of the 4 entries you added in your commit.

And it's already possible to revert to the original song though jukebox. I'll merge this PR despite the song collision. There isn't much to do about it and I guess it's not that big of a problem if it's already a thing in sfh and no one complains..

**Comment by eye-wave** [comment]
okay done

**Pull request merged**
